# This file was generated by GoReleaser. DO NOT EDIT.
cask "june" do
  name "june"
  desc "A read-only TUI for viewing Claude Code subagent activity"
  homepage "https://github.com/sky-xo/june"
  version "0.5.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "june"

  on_macos do
    on_intel do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_darwin_amd64.tar.gz"
      sha256 "7dc28ab264cf3617e9eda65a55a38c64083f61861eebf9685f648f7ae5d3bab6"
    end
    on_arm do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_darwin_arm64.tar.gz"
      sha256 "ac1b379c9139de3b3a7184dbf496914288e93964e04fb77d3487f86dc277da08"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_linux_amd64.tar.gz"
      sha256 "5647e167f6b435f1bd263b2a17da7122aac2df0e93b5e4f59591b36458de8528"
    end
    on_arm do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_linux_arm64.tar.gz"
      sha256 "e85f2cd6b7f243db3af3ade280a8ea1d5a9251dd6e159ee8d77b17e4b9da6ae0"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/june"]
  end

  # No zap stanza required
end
