# This file was generated by GoReleaser. DO NOT EDIT.
cask "june" do
  name "june"
  desc "A read-only TUI for viewing Claude Code subagent activity"
  homepage "https://github.com/sky-xo/june"
  version "0.5.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "june"

  on_macos do
    on_intel do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_darwin_amd64.tar.gz"
      sha256 "96a5499bc355069e9501e8c3298903a4ab345484b7334a2ff9fef48c6ff83f89"
    end
    on_arm do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_darwin_arm64.tar.gz"
      sha256 "d10081118d01469c44b9a171233115ca57ad17a286559b17940d04b57aea641e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_linux_amd64.tar.gz"
      sha256 "9324b0748090f708ede426ca3734ae2dc967173c11063149beac2e743c8f5343"
    end
    on_arm do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_linux_arm64.tar.gz"
      sha256 "6bdacbbb2d3c1ec03740c902cc595049712470e853a2bd1398504ba230944f28"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/june"]
  end

  # No zap stanza required
end
