# This file was generated by GoReleaser. DO NOT EDIT.
cask "june" do
  name "june"
  desc "A read-only TUI for viewing Claude Code subagent activity"
  homepage "https://github.com/sky-xo/june"
  version "0.5.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "june"

  on_macos do
    on_intel do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_darwin_amd64.tar.gz"
      sha256 "8b1948237e081e85493629f533a57d91f00426e0932464d16606e72df7969b3f"
    end
    on_arm do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_darwin_arm64.tar.gz"
      sha256 "cf3a2e41e6858989e53da9fd0c3add1c0e9ba91edd67dc6ad40b284a290a09f3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_linux_amd64.tar.gz"
      sha256 "5749f727cfb0f6816ac3f35aef49e0110cf2e47a7d465f3769e995a2131183bd"
    end
    on_arm do
      url "https://github.com/sky-xo/june/releases/download/v#{version}/june_#{version}_linux_arm64.tar.gz"
      sha256 "671eea209edddeeab0909904ae8f6d3ed3c368c8aa7ee5e58e32a1c475743588"
    end
  end

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/june"]
  end

  # No zap stanza required
end
